import re
src = open('js/render.js', encoding='utf-8').read()
m = re.search(r'const skyVS = `(.*?)`;', src, re.DOTALL)
skyVS_body = m.group(1)
m = re.search(r'const skyFS = `(.*?)`;\n', src, re.DOTALL)
skyFS_body = m.group(1)
print('--- skyVS ---')
print('  has out vec3 vDir:', 'out vec3 vDir' in skyVS_body)
print('  has varying:', 'varying' in skyVS_body)
print('--- skyFS ---')
print('  has in vec3 vDir:', 'in vec3 vDir' in skyFS_body)
print('  has varying:', 'varying' in skyFS_body)
print('  has out vec4 fragColor:', 'out vec4 fragColor' in skyFS_body)
print('  writes fragColor:', 'fragColor = vec4(sky' in skyFS_body)